baseURL: https://alexanderscheuer.netlify.app/
title: Alex Scheuer | Portfolio
theme: somrat
paginate: '6'
summaryLength: '10'
disableLanguages: []
googleAnalytics: ''
disqusShortname: ''
outputs:
  home: HTML
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  author: Alexander Scheuer
  description: This is meta description
  favicon: images/AScheuer-icon_white.png
  logo_dark: images/AScheuer-logos_black.png
  logo_light: images/AScheuer-logos_white.png
  logo_width: 250px
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap
      - link: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css
      - link: plugins/hover/hover.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/owl-carousel/owl.carousel.min.css
      - link: plugins/owl-carousel/owl.theme.default.min.css
      - link: plugins/text-animation/text-animation.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/wow.min.js
      - link: plugins/text-animation/text-animation.js
      - link: plugins/jquery.waypoints.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/owl-carousel/owl.carousel.min.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    - icon: fab fa-facebook-f
      link: https://www.facebook.com/alex.scheuer.79
    #- icon: fab fa-twitter
    #  link: https://twitter.com/somratpro
    - icon: fab fa-instagram
      link: https://www.instagram.com/alexpscheuer/?hl=en
    - icon: fab fa-github
      link: https://github.com/scheuer98
    - icon: fab fa-linkedin
      link: https://www.linkedin.com/in/alexander-scheuer/
Languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2022 London Business School x hugo theme by [somrat](https://somrat.netlify.com)
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: About me
          pre: '#'
          url: about
          weight: 2
        - name: R Projects
          url: blog
          weight: 3
        - name: Services
          pre: '#'
          url: service
          weight: 4
        - name: Education & Projects
          pre: '#'
          url: portfolio
          weight: 5
        - name: Testimonial
          pre: '#'
          url: testimonial
          weight: 6
        - name: Contact
          pre: '#'
          url: contact
          weight: 7
    weight: 1
  #fr:
  #  contentDir: content/french
  #  copyright: Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)
  #  home: Accueil
  #  languageCode: fr-fr
  #  languageName: Fr
  #  menu:
  #    main:
  #      - name: Home
  #        url: /
  #        weight: 1
  #      - name: About me
  #        pre: '#'
  #        url: about
  #        weight: 2
  #      - name: Service
  #        pre: '#'
  #        url: service
  #        weight: 3
  #      - name: Portfolio
  #        pre: '#'
  #        url: portfolio
  #        weight: 4
  #      - name: Testimonial
  #        pre: '#'
  #        url: testimonial
  #        weight: 5
  #      - name: Contact
  #        pre: '#'
  #        url: contact
  #        weight: 6
  #  weight: 2